version: '3.9'
services:
  banco-dados:
    image: 'postgres:15.4'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: willian
      POSTGRES_DB: tododocker
    ports: 
      - 9090:5432
    expose:
      - 9090
    networks: 
     - rede-teste
  todo-docker:
    image: wbogler/tododocker:0.0.1-snapshot
    build:
      context: .
    container_name: app
    restart: always
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://banco-dados:5432/tododocker
      SPRING.DATASOURCE.USERNAME: willian
      SPRING.DATASOURCE.PASSWORD: admin123
    ports: 
     - 8081:8080
    command: mvn spring-boot:run
    depends_on: 
     - banco-dados
    networks: 
     - rede-teste

networks:
  rede-teste:
    driver: bridge