version: '3.9'
services:
  banco-dados:
    image: 'postgres:latest'
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: willian
      POSTGRES_DB: tododocker
    ports: 
     - 9090:9090
    expose:
     - 9090
    networks: 
     - rede-teste
  todo-docker:
    image: wbogler/tododocker:0.0.1-snapshot
    build:
      context: .
    container_name: app
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: JDBC:POSTGRESQL://banco-dados:9090/tododocker
      SPRING.DATASOURCE.USERNAME: willian
      SPRING.DATASOURCE.PASSWORD: admin123
    ports: 
     - 8081:8081
    command: mvn spring-boot:run
    depends_on: 
     - banco-dados
    networks: 
     - rede-teste

networks:
  rede-teste:
    driver: bridge